//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;

    public partial class BuyerRequest
    {
        public int ID { get; set; }
        public int NoteID { get; set; }
        public int BuyerID { get; set; }
        public int SellerID { get; set; }
        public string NoteTitle { get; set; }
        public string Category { get; set; }
        public int Price { get; set; }
        public string BuyerEmailID { get; set; }
        public string SellType { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public string PhoneNumber { get; set; }

        public virtual User User { get; set; }
        public virtual NoteDetail NoteDetail { get; set; }
        public virtual User User1 { get; set; }
    }
}
