
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteMarketPlace.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class NoteDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoteDetail()
        {
            this.BuyerRequests = new HashSet<BuyerRequest>();
            this.Feedbacks = new HashSet<Feedback>();
            this.NoteAttachements = new HashSet<NoteAttachement>();
            this.SpamReports = new HashSet<SpamReport>();
        }

        public int NoteID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ActionedBy { get; set; }
        public int NoteStatus { get; set; }
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int Category { get; set; }
        public string BookPicture { get; set; }
        public Nullable<int> NoteType { get; set; }
        public Nullable<int> NumberOfPages { get; set; }

        [Required]
        [Display(Name = "Note Description")]
        public string NotesDescription { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<int> Country { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }

        [Required]
        [Display(Name = "Sell For")]
        public bool IsPaid { get; set; }

        public Nullable<int> SellPrice { get; set; }
        public string NotePreview { get; set; }
        public Nullable<int> NoteSize { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }

        public HttpPostedFileBase PictureFile { get; set; }
        public HttpPostedFileBase NoteFile { get; set; }
        public HttpPostedFileBase PreviewFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuyerRequest> BuyerRequests { get; set; }
        public virtual Country Country1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
   
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteAttachement> NoteAttachements { get; set; }
        public virtual NoteCategory NoteCategory { get; set; }
        public virtual NoteStatu NoteStatu { get; set; }
        public virtual NoteType NoteType1 { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpamReport> SpamReports { get; set; }
    }
}
